# GoReleaser configuration for dnsres
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Note: Tests are run in CI before release workflow triggers

builds:
  # Main CLI binary
  - id: dnsres
    main: ./cmd/dnsres
    binary: dnsres
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

  # TUI binary
  - id: dnsres-tui
    main: ./cmd/dnsres-tui
    binary: dnsres-tui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: default
    # Archive automatically includes all binaries from all builds
    # Only tar.gz for Homebrew compatibility (it can't handle multiple formats per OS/Arch)
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - INSTALL.md
      - docs/*.md
      - examples/*
      - completions/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: mikesale
    name: dnsres
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## dnsres {{ .Tag }} ({{ .Date }})
    
    DNS resolution monitoring tool with health checks, metrics, and TUI.
  footer: |
    ---
    
    **Full Changelog**: https://github.com/mikesale/dnsres/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ### Installation
    
    **Homebrew (macOS/Linux):**
    ```bash
    brew install mikesale/dnsres/dnsres
    ```
    
    **Debian/Ubuntu:**
    ```bash
    wget https://github.com/mikesale/dnsres/releases/download/{{ .Tag }}/dnsres_{{ .Version }}_Linux_x86_64.deb
    sudo dpkg -i dnsres_{{ .Version }}_Linux_x86_64.deb
    ```
    
    **RHEL/Fedora/CentOS:**
    ```bash
    wget https://github.com/mikesale/dnsres/releases/download/{{ .Tag }}/dnsres_{{ .Version }}_Linux_x86_64.rpm
    sudo rpm -i dnsres_{{ .Version }}_Linux_x86_64.rpm
    ```
    
    **Direct Install Script:**
    ```bash
    curl -sSL https://raw.githubusercontent.com/mikesale/dnsres/main/install.sh | bash
    ```
    
    **Manual Download:**
    Download the appropriate binary for your platform from the assets below, extract it, and run.
    
    For detailed installation instructions, see [INSTALL.md](https://github.com/mikesale/dnsres/blob/main/INSTALL.md)

# Homebrew formula (stored in main repository)
# Users install with: brew install mikesale/dnsres/dnsres
brews:
  - repository:
      owner: mikesale
      name: dnsres
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    ids:
      - default
    commit_author:
      name: goreleaserbot
      email: mike.sale@gmail.com
    homepage: https://github.com/mikesale/dnsres
    description: DNS resolution monitoring tool with health checks, metrics, and TUI
    license: GPL-3.0
    install: |
      bin.install "dnsres"
      bin.install "dnsres-tui"
      etc.install "examples/config.json" => "dnsres/config.json.example"
      bash_completion.install "completions/dnsres.bash" => "dnsres"
      zsh_completion.install "completions/dnsres.zsh" => "_dnsres"
      fish_completion.install "completions/dnsres.fish"
      # Also install completions for dnsres-tui
      bash_completion.install "completions/dnsres.bash" => "dnsres-tui"
      zsh_completion.install "completions/dnsres.zsh" => "_dnsres-tui"
      fish_completion.install "completions/dnsres.fish" => "dnsres-tui.fish"
    caveats: |
      Two binaries are installed:
        • dnsres: CLI for continuous monitoring
        • dnsres-tui: Interactive terminal UI

      Configuration:
        Default config location: ~/.config/dnsres/config.json
        Example config: /usr/local/etc/dnsres/config.json.example

      Quick start:
        dnsres example.com          # CLI mode
        dnsres-tui example.com      # Interactive TUI mode

      Documentation: https://github.com/mikesale/dnsres
      Issues: https://github.com/mikesale/dnsres/issues

# Linux packages (DEB and RPM)
nfpms:
  - id: packages
    package_name: dnsres
    # IDs is the new way to reference builds (not 'builds')
    ids:
      - dnsres
      - dnsres-tui
    vendor: Mike Sale
    homepage: https://github.com/mikesale/dnsres
    maintainer: Mike Sale <mike.sale@gmail.com>
    description: DNS resolution monitoring tool with health checks, metrics, and TUI
    license: GPL-3.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      # Example configuration
      - src: examples/config.json
        dst: /etc/dnsres/config.json.example
        type: config
      # Documentation
      - src: README.md
        dst: /usr/share/doc/dnsres/README.md
      - src: INSTALL.md
        dst: /usr/share/doc/dnsres/INSTALL.md
      - src: LICENSE
        dst: /usr/share/doc/dnsres/LICENSE
      # Bash completions
      - src: completions/dnsres.bash
        dst: /usr/share/bash-completion/completions/dnsres
      - src: completions/dnsres.bash
        dst: /usr/share/bash-completion/completions/dnsres-tui
      # Zsh completions
      - src: completions/dnsres.zsh
        dst: /usr/share/zsh/site-functions/_dnsres
      - src: completions/dnsres.zsh
        dst: /usr/share/zsh/site-functions/_dnsres-tui
      # Fish completions
      - src: completions/dnsres.fish
        dst: /usr/share/fish/vendor_completions.d/dnsres.fish
      - src: completions/dnsres.fish
        dst: /usr/share/fish/vendor_completions.d/dnsres-tui.fish
    scripts:
      postinstall: scripts/postinstall.sh

# Snap packages
# Disabled for now - requires snapcraft installed in CI environment
# snapcrafts:
#   - id: snap
#     ids:
#       - dnsres
#       - dnsres-tui
#     name: dnsres
#     summary: DNS resolution monitoring tool
#     description: |
#       dnsres is a DNS resolution monitoring tool with health checks, 
#       Prometheus metrics, and an interactive terminal UI (TUI).
#     license: GPL-3.0
#     grade: stable
#     confinement: classic
#     publish: false

# Announcement for release notes
announce:
  skip: '{{gt .Patch 0}}'  # Skip announcements for patch releases
