# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsres < Formula
  desc "DNS resolution monitoring tool with health checks, metrics, and TUI"
  homepage "https://github.com/mikesale/dnsres"
  version "1.2.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mikesale/dnsres/releases/download/v1.2.0/dnsres_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "d28b55fc5bc281c4d3ae52332738471d2177a1937a7c29143e3dc840fe278ed7"

      def install
        bin.install "dnsres"
        bin.install "dnsres-tui"
        etc.install "examples/config.json" => "dnsres/config.json.example"
        bash_completion.install "completions/dnsres.bash" => "dnsres"
        zsh_completion.install "completions/dnsres.zsh" => "_dnsres"
        fish_completion.install "completions/dnsres.fish"
        # Also install completions for dnsres-tui
        bash_completion.install "completions/dnsres.bash" => "dnsres-tui"
        zsh_completion.install "completions/dnsres.zsh" => "_dnsres-tui"
        fish_completion.install "completions/dnsres.fish" => "dnsres-tui.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mikesale/dnsres/releases/download/v1.2.0/dnsres_1.2.0_Darwin_arm64.tar.gz"
      sha256 "cc0b738473ee2742556c51a3e6173a5cb96c4004431ccf28254af97f9cde3231"

      def install
        bin.install "dnsres"
        bin.install "dnsres-tui"
        etc.install "examples/config.json" => "dnsres/config.json.example"
        bash_completion.install "completions/dnsres.bash" => "dnsres"
        zsh_completion.install "completions/dnsres.zsh" => "_dnsres"
        fish_completion.install "completions/dnsres.fish"
        # Also install completions for dnsres-tui
        bash_completion.install "completions/dnsres.bash" => "dnsres-tui"
        zsh_completion.install "completions/dnsres.zsh" => "_dnsres-tui"
        fish_completion.install "completions/dnsres.fish" => "dnsres-tui.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikesale/dnsres/releases/download/v1.2.0/dnsres_1.2.0_Linux_x86_64.tar.gz"
      sha256 "6e977096c2a21bdb8245be9859cf6e272a2e1f558d4232dbf06a19869f3a5db5"
      def install
        bin.install "dnsres"
        bin.install "dnsres-tui"
        etc.install "examples/config.json" => "dnsres/config.json.example"
        bash_completion.install "completions/dnsres.bash" => "dnsres"
        zsh_completion.install "completions/dnsres.zsh" => "_dnsres"
        fish_completion.install "completions/dnsres.fish"
        # Also install completions for dnsres-tui
        bash_completion.install "completions/dnsres.bash" => "dnsres-tui"
        zsh_completion.install "completions/dnsres.zsh" => "_dnsres-tui"
        fish_completion.install "completions/dnsres.fish" => "dnsres-tui.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikesale/dnsres/releases/download/v1.2.0/dnsres_1.2.0_Linux_arm64.tar.gz"
      sha256 "6c0c7c10ca6b26261711f60fd5754a1d093847983613ba32a0e6b1b75520d480"
      def install
        bin.install "dnsres"
        bin.install "dnsres-tui"
        etc.install "examples/config.json" => "dnsres/config.json.example"
        bash_completion.install "completions/dnsres.bash" => "dnsres"
        zsh_completion.install "completions/dnsres.zsh" => "_dnsres"
        fish_completion.install "completions/dnsres.fish"
        # Also install completions for dnsres-tui
        bash_completion.install "completions/dnsres.bash" => "dnsres-tui"
        zsh_completion.install "completions/dnsres.zsh" => "_dnsres-tui"
        fish_completion.install "completions/dnsres.fish" => "dnsres-tui.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Two binaries are installed:
        • dnsres: CLI for continuous monitoring
        • dnsres-tui: Interactive terminal UI

      Configuration:
        Default config location: ~/.config/dnsres/config.json
        Example config: /usr/local/etc/dnsres/config.json.example

      Quick start:
        dnsres example.com          # CLI mode
        dnsres-tui example.com      # Interactive TUI mode

      Documentation: https://github.com/mikesale/dnsres
      Issues: https://github.com/mikesale/dnsres/issues
    EOS
  end
end
